schema = 3

[mod]
  [mod."cuelang.org/go"]
    version = "v0.4.3"
    hash = "sha256-i9wampQA4Fnjfzce91SNb76WD3iEQir8VP66WJdTNGY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.2.0"
    hash = "sha256-JaGYNQwDxFCsLwzYVoJY4RUpP4dtiRlV14t2dVAg4oQ="
  [mod."github.com/atotto/clipboard"]
    version = "v0.1.4"
    hash = "sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk="
  [mod."github.com/aws/constructs-go/constructs/v10"]
    version = "v10.1.299"
    hash = "sha256-f4WXQULhCEnrwW5AbRta4p2CTr+CaAbLVkiIJIc/z9M="
  [mod."github.com/aws/jsii-runtime-go"]
    version = "v1.79.0"
    hash = "sha256-QjctI9rjVZaAXrsuG9IWwG0yjVMikYqWTg/jdI851S0="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/bufbuild/connect-go"]
    version = "v1.5.2"
    hash = "sha256-tZNMxheADUhHBOKtFBezOYiLWTR0Ztviq05ogh+uwXw="
  [mod."github.com/bytedance/sonic"]
    version = "v1.8.6"
    hash = "sha256-XRYME6pJ+PsKr3vRlMB+ulL2boO3yxRgLnUPib5h+YE="
  [mod."github.com/cdktf/cdktf-provider-tfe-go/tfe/v5"]
    version = "v5.0.1"
    hash = "sha256-FjzjUYhEFzVnoHINIFepFHBkuqJHJPmwmCik3unBaW8="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.15.0"
    hash = "sha256-DyphnjmsV0+sXdhXcjP/4t5pKqDFokKyqEcMCnK1mTw="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.23.2"
    hash = "sha256-ZIjkMtD5izq+8h5F6Po3FER28hS5Rh1hJsKozoinMX8="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.7.1"
    hash = "sha256-GdPbyi762tGmU0ASLv76/DDjOubYp6K1kNio/IUVUiQ="
  [mod."github.com/chenzhuoyu/base64x"]
    version = "v0.0.0-20221115062448-fe3a3abad311"
    hash = "sha256-xmONcYkIXgXomJYHR521Dr9F3XbbUM14bgf7KJ5FIFc="
  [mod."github.com/cockroachdb/apd/v2"]
    version = "v2.0.2"
    hash = "sha256-UrPHkvqVF8V78+kXKmjTHl79XsgDBnqFsje5BMYh0E4="
  [mod."github.com/containerd/console"]
    version = "v1.0.3"
    hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.10.2"
    hash = "sha256-u/FpZjxt6eAFOWB/dtFbjGnWamJ5phOwfn0frKrUuuI="
  [mod."github.com/emicklei/proto"]
    version = "v1.11.1"
    hash = "sha256-/Zp1CBrQkjQB6XR7yJ+jId6ZRYl97SSwJ3Ew9zHjxRU="
  [mod."github.com/evanphx/json-patch/v5"]
    version = "v5.6.0"
    hash = "sha256-9P31eky/JuDLlVmKUk4+SfoXWLuJqANm5gSMDzR82No="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.6.0"
    hash = "sha256-DQesOCweQPEwmAn6s7DCP/Dwy8IypC+osbpfsvpkdP0="
  [mod."github.com/gin-contrib/sse"]
    version = "v0.1.0"
    hash = "sha256-zYbMTao+1F+385Lvsba9roLmmt9eYqr57sUWo0LCVhw="
  [mod."github.com/gin-gonic/gin"]
    version = "v1.9.0"
    hash = "sha256-vLkfoIeChmCKcLxRfp080tO0/2n6QBoCLxlFdUEEv+s="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-logr/zapr"]
    version = "v1.2.3"
    hash = "sha256-bnUFAqMcSw2Tp0kjmOjq9MNvfVAmt/cFU7KYtTHCHeM="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.12.0"
    hash = "sha256-aRJb44OvM6/zSnVK+SFWKrJeOBnwpjXkUlbietp+DVg="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.2"
    hash = "sha256-6fMD2/Rku8HT0zDdeA23pX0YxbohiIOC8OJNYbylJTQ="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/gnostic"]
    version = "v0.6.9"
    hash = "sha256-kFE3mdJjOC9Wr/6/C6MMtx7j1V0ALS6oDjLaVSjN1wY="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hashicorp/terraform-cdk-go/cdktf"]
    version = "v0.15.5"
    hash = "sha256-euFKA7yKjWy6kZpVokCWCJvc6a5BdwFsZ8hkbcgewmA="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.15"
    hash = "sha256-HyN1PxCZW2IRns9VDkwxMHtDvdDwaRgat0wcHf53B0w="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.4"
    hash = "sha256-EjWkW6py3nYOut+YY9waTI2OegIFQWuJRS1hZ+F+obU="
  [mod."github.com/leodido/go-urn"]
    version = "v1.2.2"
    hash = "sha256-ymlr4WSk8z9VRKesluA9PZwRuwSXMVz+z5aOS34dVuI="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.18"
    hash = "sha256-QpIn0DSggtBn2ocyj0RlXDKLK5F5KZG1/ogzrqBCjF8="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/mpvl/unique"]
    version = "v0.0.0-20150818121801-cbe035fff7de"
    hash = "sha256-kWdg8qhWQem2xCzwQKbQ0dmwA8D5Zwe6owPIgSMSIB4="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.1"
    hash = "sha256-vbltynBfzDXd+XO/naRmAeh71o8jlT7Y4fHA1Jj6qg8="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.6.0"
    hash = "sha256-IsO7myZW6jndhAe2ZwG3LObtQpuOAJVTVeZ3zV4kAX0="
  [mod."github.com/onsi/gomega"]
    version = "v1.24.1"
    hash = "sha256-REfxQTDRcO23GnmJfOW8/MmPJf9oE2grVvvGiC1eSbo="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.7"
    hash = "sha256-N/bMEQkqdlkmRN0bKbdifEquKHEPaxltX8LTmhOkUGc="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.42.0"
    hash = "sha256-dJqoPZKtY2umWFWwMeRYY9I2JaFlpcMX4atkEcN5+hs="
  [mod."github.com/prometheus/procfs"]
    version = "v0.9.0"
    hash = "sha256-imZN+1HRpMvgmrot2V+AK5ueYLmsp49vZfHtx2N6Wek="
  [mod."github.com/protocolbuffers/txtpbfmt"]
    version = "v0.0.0-20230328191034-3462fbc510c0"
    hash = "sha256-vvkZWDGrId164K6jhMXNa5BtOxQSgFDhMACGAH+9F08="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.4"
    hash = "sha256-B8tbL9K6ICLdm0lEhs9+h4cpjAfvFtNiFMGvQZmw0bM="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/spf13/afero"]
    version = "v1.9.5"
    hash = "sha256-+XECQxkx0P+ZaQDm4dQ6ItMtHMj+2uNemEC18dsdor0="
  [mod."github.com/spf13/cast"]
    version = "v1.5.0"
    hash = "sha256-Pdp+wC5FWqyJKzyYHb7JCcV9BoJk/sxQw6nLyuLJvuQ="
  [mod."github.com/spf13/cobra"]
    version = "v1.6.1"
    hash = "sha256-80B5HcYdFisz6QLYkTyka7f9Dr6AfcVyPwp3QChoXwU="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.15.0"
    hash = "sha256-FvpbekXegcdWNbek/vs2zakgRsT5FROF8O8fhn5DNpI="
  [mod."github.com/subosito/gotenv"]
    version = "v1.4.2"
    hash = "sha256-LnrDR1k/AoCFWBMcU7vQsoQLkZ65evT2hoQHLDudTsg="
  [mod."github.com/twitchyliquid64/golang-asm"]
    version = "v0.15.1"
    hash = "sha256-HLk6oUe7EoITrNvP0y8D6BtIgIcmDZYtb/xl/dufIoY="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.11"
    hash = "sha256-hfcj+YsznH6MeERSdIPjSrsM7gbDcIzH/TbgHzYbPww="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.4"
    hash = "sha256-4he5sGi0uj1LogdqvgpvN8b7p6qlKMGuWXRFzh+FK8s="
  [mod."go.uber.org/atomic"]
    version = "v1.10.0"
    hash = "sha256-E6UEDc1eh/cLUFd+J86cDesQ0B8wEv/DdaAVKb+x2t8="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.24.0"
    hash = "sha256-yLzjFbMWnc5b033gcPLGP0KY1xWPJ3sjnUG/RndmC3o="
  [mod."golang.org/x/arch"]
    version = "v0.3.0"
    hash = "sha256-Gus5o3I0+arNjRFglTP5FfCi0NDwKAUT/N3WtdhnLMQ="
  [mod."golang.org/x/crypto"]
    version = "v0.7.0"
    hash = "sha256-Yc4casCQyfOgIr48FV+NI9qhanhBuYnkph5iI7rDyZE="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20210508222113-6edffad5e616"
    hash = "sha256-U4o4PZ8KRpwbUN+E0VwewWNCiK5OGeBIpAMLJEbO9Ng="
  [mod."golang.org/x/mod"]
    version = "v0.9.0"
    hash = "sha256-Lk+O2L4cTlie5j6iO5P3jrkYe2u94Y/a1OFjOBbivIE="
  [mod."golang.org/x/net"]
    version = "v0.8.0"
    hash = "sha256-2cOtqa7aJ5mn64kZ+8+PVjJ4uGbhpXTpC1vm/+iaZzM="
  [mod."golang.org/x/oauth2"]
    version = "v0.6.0"
    hash = "sha256-M6yqSRqMcgp4bOCa4ey8/13z/0BrjQgyUQXJZU1hmnw="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
  [mod."golang.org/x/term"]
    version = "v0.6.0"
    hash = "sha256-Ao0yXpwY8GyG+/23dVfJUYrfEfNUTES3RF45v1VhUAk="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."golang.org/x/tools"]
    version = "v0.7.0"
    hash = "sha256-ZEjfFulQd6U9r4mEJ5RZOnW49NZnQnrCFLMKCgLg7go="
  [mod."gomodules.xyz/jsonpatch/v2"]
    version = "v2.2.0"
    hash = "sha256-PhyOjXzIs3M0HXoVTWXQnqXL4S0s/DlE0IfX6A+oBJc="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.30.0"
    hash = "sha256-Y07NKhSuJQ2w7F7MAINQyBf+/hdMHOrxwA3B4ljQQKs="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/api"]
    version = "v0.26.3"
    hash = "sha256-youX6CPK+qKf8LC1SiqdxGY7EPygnYAn1/0DKddILhg="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.26.3"
    hash = "sha256-89Snaw6RFFg3mXf44qU52zI+/tnEnqT+/nwbwN6Leas="
  [mod."k8s.io/apimachinery"]
    version = "v0.26.3"
    hash = "sha256-yWnEgX5MW+geftt/uH5Fp+0lRiZ1uIsQDs25UBf84z4="
  [mod."k8s.io/client-go"]
    version = "v0.26.3"
    hash = "sha256-OVb3DBsnnLoH1E9gIO8/MGxQuDpveTeJvr9GodERC10="
  [mod."k8s.io/component-base"]
    version = "v0.26.3"
    hash = "sha256-jbH93Em++aH+LtDzRrJySMU0KLwC3BZoIZdF2PoN9iY="
  [mod."k8s.io/klog/v2"]
    version = "v2.90.1"
    hash = "sha256-04i9N6khNBIPI2lACqKVr3lGOItGIiCZJOfhggxdK60="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20230327201221-f5883ff37f0c"
    hash = "sha256-dJyhx4uxoje0PwpAwmQ+Pic15cJWfTIwctgDmUYXrzM="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20230313181309-38a27ef9d749"
    hash = "sha256-8xLFydpKqVWRohnMgFmMqnIWKOewmFlza7HPBeQjGTo="
  [mod."sigs.k8s.io/controller-runtime"]
    version = "v0.14.6"
    hash = "sha256-VvVx7GuekIIuLjrqS+4AxcJpHniJRUrs1+yVICscI3M="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20221116044647-bc3834ca7abd"
    hash = "sha256-XDBMN2o450IHiAwEpBVsvo9e7tYZa+EXWrifUNTdNMU="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.3.0"
    hash = "sha256-RVp8vca2wxg8pcBDYospG7Z1dujoH7zXNu2rgZ1kky0="
