# permissions for end users to view blargs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: blarg-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: template-go
    app.kubernetes.io/part-of: template-go
    app.kubernetes.io/managed-by: kustomize
  name: blarg-viewer-role
rules:
- apiGroups:
  - meh.defn.dev
  resources:
  - blargs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - meh.defn.dev
  resources:
  - blargs/status
  verbs:
  - get
