# permissions for end users to edit hrnnggs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hrnngg-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: template-go
    app.kubernetes.io/part-of: template-go
    app.kubernetes.io/managed-by: kustomize
  name: hrnngg-editor-role
rules:
- apiGroups:
  - meh.defn.dev
  resources:
  - hrnnggs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meh.defn.dev
  resources:
  - hrnnggs/status
  verbs:
  - get
